### ISSUE TITLE
Design decision for `GOOD_LEAF_SIZE` value

### ISSUE THREAD

**Issue by bradleyayers** [marijnh/rope-sequence#1]
Curious how the value for `GOOD_LEAF_SIZE` is determined? Would be great to have that knowledge documented.

**Comment by marijnh** [comment]
I believe I mostly just guessed, ran a crude benchmark with a few different sizes, and went with the one that came out ahead.

**Comment by bradleyayers** [comment]
Sounds good. If you've got the benchmark handy that would be cool to include, if not 🤷🏻‍♂️

**Comment by marijnh** [comment]
I think I just ran the test suite—probably with the `SIZE` constant set higher.
