### ISSUE TITLE
index.js has an arrow function causing prosemirror not transpiled correctly for ie11

### ISSUE THREAD

**Issue by vuduo** [marijnh/rope-sequence#3]
Hi

there is an arrow function leftover in the index.js code

`this.forEach((elt, i) => result.push(f(elt, i)), from, to)`

in
```
  // :: ((element: T, index: number) → U, ?number, ?number) → [U]
  // Map the given functions over the elements of the rope, producing
  // a flat array.
  map(f, from = 0, to = this.length) {
    let result = []
    this.forEach((elt, i) => result.push(f(elt, i)), from, to)
    return result
  }
```
causing prosemirror not to work in ie11. Could you please fix this.

Best regards

**Comment by marijnh** [comment]
Which version are you using? I don't see any ES6 in dist/index.js in 1.3.2

**Comment by vuduo** [comment]
I am using prosemirror-history 1.1.2. Looks like that version uses rope-sequence 1.3.0.

In the index.js file in line 64, there is an arrow function after the forEach statement. This seems not to be transpiled correctly into the dist/index.mjs

**Comment by marijnh** [comment]
But package.json only references dist/index.js, so I'm confused why the ES6 file would be getting bundled.

**Comment by vuduo** [comment]
I am using webpack 4.41.2 for bundling. Looks like it prioritize module field over main causing it to bundle the index.mjs. So looks like i have to find a way to tell webpack to use the main field to get the dependency.

**Comment by marijnh** [comment]
module points at `dist/index.es.js`, which also does not contain the string `=>`.

**Comment by vuduo** [comment]
Now I see. Had to refetch prosemirror-history 1.1.2 for it to fetch the updated rope-sequence. Thanks for helping me out.
